apiVersion: v1
kind: Service
metadata:
  name: platforms-service-node-port
spec:
  type: NodePort
  selector:
    app: platformservice
  ports:
    - name: platformservice
      protocol: TCP
      port: 80
      targetPort: 80
